"""user.sent_photos

Revision ID: 0662b9592017
Revises: bbf2d5a3d525
Create Date: 2021-06-18 19:37:20.627381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0662b9592017'
down_revision = 'bbf2d5a3d525'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_photos', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('sent_photos')

    # ### end Alembic commands ###
